### ISSUE TITLE
Adding multiple repo's causes message loops

### ISSUE THREAD

**Issue by SteamingMutt** [Falconerd/discord-bot-github#1]
If multiple repo's are added to `config.json`, the bot will continuously send messages about the same events.

**Comment by Falconerd** [comment]
I'm working on releasing a new major update which can handle multiple repos, servers and channels correctly.

**Comment by Falconerd** [comment]
I believe this should be fixed, the usage is a bit different now, though. Would you mind seeing if it works on your end?

**Comment by SteamingMutt** [comment]
I can't seem to get it to work, it just throws errors;
```
undefined:0



SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /home/remco/GitBot/node_modules/discord-bot-github/dist/discord-bot-github.umd.js:229:22
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
```

**Comment by Falconerd** [comment]
@SteamingMutt Can you tell me what command you are using to run the bot? I just did a test and I had no problem. For now, the usage is only command line, passing in one parameter which is the config.json. The config.json structure has also changed to allow easier reporting to multiple servers/channels.

```
$ npm install discord-bot-github
$ ./node_modules/discord-bot-github ./config.json
> [INFO] Discord GitHub Bot listening for changes...
```

**Comment by SteamingMutt** [comment]
I used NodeJS to start the script (`node .`) just like the previous version.
I followed the guide in the readme and the config,json file is correct (only made 1 repo for testing purposes, and copied the template from the readme)
But if I replicate your steps in  https://github.com/Falconerd/discord-bot-github/issues/1#issuecomment-168990605, it trows this:
```
/home/remco/GitBot/node_modules/discord-bot-github/dist/discord-bot-github.umd.js:242
        this.email = config.email;
                           ^

TypeError: Cannot read property 'email' of undefined
    at DiscordBotGithub.setup (/home/remco/GitBot/node_modules/discord-bot-github/dist/discord-bot-github.umd.js:242:28)
    at new DiscordBotGithub (/home/remco/GitBot/node_modules/discord-bot-github/dist/discord-bot-github.umd.js:234:14)
    at /home/remco/GitBot/node_modules/discord-bot-github/dist/discord-bot-github.umd.js:650:15
    at fs (/home/remco/GitBot/node_modules/discord-bot-github/dist/discord-bot-github.umd.js:2:66)
    at Object.<anonymous> (/home/remco/GitBot/node_modules/discord-bot-github/dist/discord-bot-github.umd.js:5:2)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

```

**Comment by Falconerd** [comment]
My bad, the sample config was missing the first "{", that may be the issue. I've also tested with using git instead of npm.

```
$ git clone git@github.com:Falconerd/discord-bot-github.git .
$ npm install
[copy or create config.json to .]
$ node . config.json
> [INFO] Discord GitHub Bot listening for changes...
```
Can you show me a copy of your config.json with the sensitive data removed?

**Comment by SteamingMutt** [comment]
```
{
  "interval": 5000,
  "email": "",
  "password": "",
  "token": "",
  "avatar": "",
  "subscriptions": [
    {
      "repository": "SteamingMutt/DougleyBot",
      "servers": [
        {
          "id": "",
          "invite": "https://discord.gg/",
          "channels": [
            {
              "name": "general",
              "events": [
                "Push",
                "PullRequest"
              ]
            }
          ]
        },
    {
      "repository": "SteamingMutt/DougleyBot2.0",
      "servers": [
        {
          "id": "",
          "invite": "https://discord.gg/",
          "channels": [
            {
              "name": "general",
              "events": [
                "Push",
                "PullRequest"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Falconerd** [comment]
Thanks, it seems you're missing one bracket and one brace in the first repository setting. Let me know if that helps. Otherwise, I don't see anything wrong with it.

```json
{
  "interval": 5000,
  "email": "",
  "password": "",
  "token": "",
  "avatar": "",
  "subscriptions": [
    {
      "repository": "SteamingMutt/DougleyBot",
      "servers": [
        {
          "id": "",
          "invite": "https://discord.gg/",
          "channels": [
            {
              "name": "general",
              "events": [
                "Push",
                "PullRequest"
              ]
            }
          ]
        } <---
      ] <---
    },
    {
      "repository": "SteamingMutt/DougleyBot2.0",
      "servers": [
        {
          "id": "",
          "invite": "https://discord.gg/",
          "channels": [
            {
              "name": "general",
              "events": [
                "Push",
                "PullRequest"
              ]
            }
          ]
        }
      ]
    }
  ]
}```

**Comment by SteamingMutt** [comment]
Yup, seems to work fine after your help, thanks.
